encryption_key = 'lab_1/task1_encryption/key.json'
decryption_key = 'lab_1/task2_decryption/key.json'
encryption_input = 'lab_1/task1_encryption/input.txt'
decryption_input = 'lab_1/task2_decryption/input.txt'
encryption_output = 'lab_1/task1_encryption/output.txt'
decryption_output = 'lab_1/task2_decryption/output.txt'
decryption_frequency = 'lab_1/task2_decryption/frequency.json'
