encrytion_key = 'lab_1/task1_encryption/key.json'
decryption_key = 'lab_1/task2_decryption/key.json'
encrytion_input = 'lab_1/task1_encryption/input.txt'
decryption_input = 'lab_1/task2_decryption/input.txt'
encrytion_output = 'lab_1/task1_encryption/output.txt'
decryption_otput = 'lab_1/task2_decryption/output.txt'